### ISSUE TITLE
Compile List of Prebuilts for Compounds_Core

### ISSUE THREAD

**Issue by thisisphan** [elixirlearners/compounds#1]
Research and identify potential prebuilts to include.

**Comment by calebgasser** [comment]
> - **Accordian**: This is a basic UI element between libraries and is not readily avaiable. It
> shouldn't be too hard to impliment and has a lot of uses.
> - **Alert**: This is a basic UI element between libraries. Phoenix does have built in alerts
> for their inputs, but these could be more general and have interop with Phoenix's.
> - **Avatar**: This is common between libraries and would be trivial to impliment.
> - **Button**: Very common in libraries. Trivial, basically just wrap our default styles around
> it.
> - **Card**: Common element and very useful. Easy to impliment.
> - **Checkbox**: Very common and very useful. Easy to impliment.
> - **Combobox**: I find myself needing these fairly offten and are not always straight forward
> to impliment.
> - **Context Menu (right click)**: This one I just think is neat to have.
> - **Data table**: I think this one is too useful not to have.
> - **Dialog**: Too useful not to have.
> - **Drawer**: I think this would be very usefull, find myself making these fairly offten.
> - **Dropdown**: Basic, easiy to impliment, useful.
> - **Form**: Must have, very useful.
> - **Input**: Too basic not to have.
> - **Label**: Too basic not to have.
> - **Menu**: Easy, useful, must have.
> - **Top Navigation**: Almost required by every site, must have.
> - **Bottom Navigation**: ^^^ Same as above.
> - **Popover**: Very common, must have.
> - **Radio Group**: Too common not to have.
> - **Separator**: Easy, might as well have it.
> - **Sheet/Paper**: Easy, basic, most all have some form of it.
> - **Slider**: Too basic not to have.
> - **Table**: Required
> - **Tabs**: Super common, must include.
> - **Textarea**: This goes with input and form.
> - **Toast**: Too basic not to have.
> - **Toggle**: Once again, too basic not to have.
> - **Tooltip**: Too useful not to have.
