### ISSUE TITLE
Add Geist font

### ISSUE THREAD

**Issue by cyanff** [elixirlearners/compounds#45]
So far, we've been using the default, system sans serif fonts.
Since we'll be using a Neo-grotesque for the 1.0 release, we should add and start using Geist now to get a better feel for what the final version would look like.

https://vercel.com/font

**Comment by calebgasser** [comment]
In my current Input branch I added all the Geist colors to the Tailwind theme. I'll can break that off into a separate branch and do a pull request for it.

**Comment by cyanff** [comment]
Yeah, that'd be great :)
